### ISSUE TITLE
clean _txt function error

### ISSUE THREAD

**Issue by gabbygab1233** [Jcharis/neattext#17]
![image](https://user-images.githubusercontent.com/37177883/109658334-6d61a900-7ba1-11eb-93e8-20c21267f2fd.png)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-71-e1a0937b7e76> in <module>
      1 from neattext.functions import clean_text
----> 2 clean_text(docx)

/opt/conda/lib/python3.7/site-packages/neattext/functions/functions.py in clean_text(text, puncts, stopwords, urls, emails, numbers, emojis, special_char, phone_num, non_ascii, multiple_whitespaces, contractions, currency_symbols, custom_pattern)
    470         text = remove_punctuations(text)
    471     if stopwords:
--> 472         text = remove_stopwords(text)
    473     if emails:
    474         text = remove_emails(text)

/opt/conda/lib/python3.7/site-packages/neattext/functions/functions.py in remove_stopwords(text, lang)
    120         stopwords_in_use = STOPWORDS_en
    121 
--> 122     result = [word for word in text.split() if word.lower() not in stopwords_in_use]
    123     return " ".join(result)
    124 

AttributeError: 'TextFrame' object has no attribute 'split'

**Comment by Jcharis** [comment]
Hello  @gabbygab1233 thanks for reporting this issue.
I guess the right approach for  this is to pass the **_clean_text_** on the   _**.text**_ attribute of the TextFrame.
![Screenshot from 2021-03-02 17-42-40](https://user-images.githubusercontent.com/21055925/109674522-a852e500-7b7f-11eb-9229-f00549146824.png)

Hope this helps

**Comment by gabbygab1233** [comment]
Why the clean_text function doesn't remove the comma and period?

**Comment by Jcharis** [comment]
Hi @gabbygab1233 , the clean_text has several parameters that one can use for cleaning a given text. You will have to set it to True to enable this feature.
Eg.
```python
In [18]: from neattext.functions import clean_text

In [19]: mytext = "This is a sample example; with a period."

In [20]: # Default Settings: Punctuations are set as False

In [21]: clean_text(mytext)
Out[21]: 'sample example; period.'

In [22]: # Set Punctuations to True eg puncts=True

In [23]: clean_text(mytext,puncts=True)
Out[23]: 'sample example period'
In[24]: # Get All Params
In [24]: ?clean_text

```
Hope this helps

**Comment by gabbygab1233** [comment]
Oh niceeee! Thanks

**Comment by gabbygab1233** [comment]
Oh niceeee! Thanks
